#include <stdio.h>
typedef void TestFn(void);
typedef struct{
	char* name; 
	TestFn* fn;
} Test;

//code to be updated starts
TestFn setup,teardown,fixtureSetup,fixtureTearDown,test_for_createStack_create_an_empty_list_and_gives_top_and_tail_is_null,test_create_node_to_create_for_int_data_and_gives_next_to_null,test_for_push_an_integer_element_in_top_of_the_stack_and_gives_count_is_1,test_for_push_an_integer_element_top_of_the_stack,test_for_push_integer_element_to_top_of_the_stack_for_3_elements,test_for_push_an_charecter_element_in_top_of_the_stack_and_gives_count_is_1,test_for_push_an_charecter_element_top_of_the_stack,test_for_push_charecterr_element_to_top_of_the_stack_for_3_elements,test_for_push_a_float_element_in_top_of_the_stack_and_gives_count_is_1,test_for_push_a_float_element_top_of_the_stack,test_for_push_float_element_to_top_of_the_stack_for_3_elements,test_for_push_a_string_element_in_top_of_the_stack_and_gives_count_is_1,test_for_push_an_string_type_element_top_of_the_stack,test_for_push_string_element_to_top_of_the_stack_for_3_elements,test_for_pop_an_integer_element_in_top_of_the_stack_and_gives_count_is_0,test_for_pop_an_integer_element_in_top_of_the_stack_and_returns_refrence_of_the_pop_element,test_for_pop_an_integer_element_more_than_2_in_top_of_the_stack_and_returns_refrence_of_the_pop_element,test_for_pop_an_char_element_in_top_of_the_stack_and_gives_count_is_0,test_for_pop_charecter_element_in_top_of_the_stack_and_returns_refrence_of_the_pop_element,test_for_pop_charecter_element_more_than_2_in_top_of_the_stack_and_returns_refrence_of_the_pop_element,test_for_pop_float_element_in_top_of_the_stack_and_gives_count_is_0,test_for_pop_float_element_in_top_of_the_stack_and_returns_refrence_of_the_pop_element,test_for_pop_float_element_more_than_2_in_top_of_the_stack_and_returns_refrence_of_the_pop_element;
Test test[] = {"test_for_createStack_create_an_empty_list_and_gives_top_and_tail_is_null",test_for_createStack_create_an_empty_list_and_gives_top_and_tail_is_null,"test_create_node_to_create_for_int_data_and_gives_next_to_null",test_create_node_to_create_for_int_data_and_gives_next_to_null,"test_for_push_an_integer_element_in_top_of_the_stack_and_gives_count_is_1",test_for_push_an_integer_element_in_top_of_the_stack_and_gives_count_is_1,"test_for_push_an_integer_element_top_of_the_stack",test_for_push_an_integer_element_top_of_the_stack,"test_for_push_integer_element_to_top_of_the_stack_for_3_elements",test_for_push_integer_element_to_top_of_the_stack_for_3_elements,"test_for_push_an_charecter_element_in_top_of_the_stack_and_gives_count_is_1",test_for_push_an_charecter_element_in_top_of_the_stack_and_gives_count_is_1,"test_for_push_an_charecter_element_top_of_the_stack",test_for_push_an_charecter_element_top_of_the_stack,"test_for_push_charecterr_element_to_top_of_the_stack_for_3_elements",test_for_push_charecterr_element_to_top_of_the_stack_for_3_elements,"test_for_push_a_float_element_in_top_of_the_stack_and_gives_count_is_1",test_for_push_a_float_element_in_top_of_the_stack_and_gives_count_is_1,"test_for_push_a_float_element_top_of_the_stack",test_for_push_a_float_element_top_of_the_stack,"test_for_push_float_element_to_top_of_the_stack_for_3_elements",test_for_push_float_element_to_top_of_the_stack_for_3_elements,"test_for_push_a_string_element_in_top_of_the_stack_and_gives_count_is_1",test_for_push_a_string_element_in_top_of_the_stack_and_gives_count_is_1,"test_for_push_an_string_type_element_top_of_the_stack",test_for_push_an_string_type_element_top_of_the_stack,"test_for_push_string_element_to_top_of_the_stack_for_3_elements",test_for_push_string_element_to_top_of_the_stack_for_3_elements,"test_for_pop_an_integer_element_in_top_of_the_stack_and_gives_count_is_0",test_for_pop_an_integer_element_in_top_of_the_stack_and_gives_count_is_0,"test_for_pop_an_integer_element_in_top_of_the_stack_and_returns_refrence_of_the_pop_element",test_for_pop_an_integer_element_in_top_of_the_stack_and_returns_refrence_of_the_pop_element,"test_for_pop_an_integer_element_more_than_2_in_top_of_the_stack_and_returns_refrence_of_the_pop_element",test_for_pop_an_integer_element_more_than_2_in_top_of_the_stack_and_returns_refrence_of_the_pop_element,"test_for_pop_an_char_element_in_top_of_the_stack_and_gives_count_is_0",test_for_pop_an_char_element_in_top_of_the_stack_and_gives_count_is_0,"test_for_pop_charecter_element_in_top_of_the_stack_and_returns_refrence_of_the_pop_element",test_for_pop_charecter_element_in_top_of_the_stack_and_returns_refrence_of_the_pop_element,"test_for_pop_charecter_element_more_than_2_in_top_of_the_stack_and_returns_refrence_of_the_pop_element",test_for_pop_charecter_element_more_than_2_in_top_of_the_stack_and_returns_refrence_of_the_pop_element,"test_for_pop_float_element_in_top_of_the_stack_and_gives_count_is_0",test_for_pop_float_element_in_top_of_the_stack_and_gives_count_is_0,"test_for_pop_float_element_in_top_of_the_stack_and_returns_refrence_of_the_pop_element",test_for_pop_float_element_in_top_of_the_stack_and_returns_refrence_of_the_pop_element,"test_for_pop_float_element_more_than_2_in_top_of_the_stack_and_returns_refrence_of_the_pop_element",test_for_pop_float_element_more_than_2_in_top_of_the_stack_and_returns_refrence_of_the_pop_element};
char testFileName[] = {"stackADTTest.c"};
void _setup(){/*CALL_SETUP*/}
void _teardown(){/*CALL_TEARDOWN*/}
void fixtureSetup(){}
void fixtureTearDown(){}
//code to be updated ends

int testCount;
int passCount;
int currentTestFailed;

int assert_expr(int expr, const char* fileName, int lineNumber, const char* expression){
	if(expr) return 0;
	currentTestFailed = 1;
	printf("\t %s : failed at %s:%d\n",expression, fileName,lineNumber);
	return 1;
}
int assert_equal(int val1, int val2, const char* fileName, int lineNumber,const char* expr1,const char* expr2){
	if(val1 == val2) return 0;
	currentTestFailed = 1;
	printf("\t %d == %d: failed in assertEqual(%s,%s) at %s:%d\n",val1,val2,expr1,expr2, fileName,lineNumber);
	return 1;
}

void runTest(char* name, TestFn test){
	testCount++,currentTestFailed=0;
	printf("**  %s\n",name);
	_setup();
		test();
	_teardown();
	if(!currentTestFailed) passCount++;	
}
int main(int argc, char const *argv[]){		
	int i,total = sizeof(test)/sizeof(Test);	
	fixtureSetup();
	testCount=0,passCount=0;
	printf("**------ %s ------\n",testFileName);
	for (i = 0; i < total; ++i)
		runTest(test[i].name,test[i].fn);	
	printf("** Ran %d tests passed %d failed %d\n",testCount,passCount,testCount-passCount);
	fixtureTearDown();	
	return 0;
}